[package]
name = "netdmx"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
license = "MIT/Apache-2.0"
description = "Network to DMX"
readme = "README.md"
edition = "2021"

[dependencies]
rusb = "0.9.4"
clap = { version = "4.5", features = ["cargo"] }
triple_buffer = "8.1.1"
